package org.example.ticketmachine;

//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import org.example.data.Event;
import org.example.data.EventTicketMachine;

import java.awt.*;
import java.awt.event.*;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.event.*;

public class TicketMachineGui extends JFrame {
    public JButton buyTicketButton;
    public JList eventList;
    public JScrollPane eventScrollPane;
    public JTextField jcomp3;
    public JLabel dataLabel;
    public ArrayList<EventTicketMachine> eventArrayList;

    public TicketMachineGui() {
        eventArrayList = new ArrayList<>();
        guiInit();
    }

    private void guiInit() {
        String[] eventListItems = {};

        //construct components
        buyTicketButton = new JButton("buy");
        eventList = new JList(eventListItems);
        jcomp3 = new JTextField(5);
        dataLabel = new JLabel("Name");
        eventScrollPane = new JScrollPane(eventList);

        //adjust size and set layout
        setSize(400, 170);
        setLayout(null);
        setResizable(false);

        //add components
        add(buyTicketButton);
        add(eventScrollPane);
        add(jcomp3);
        add(dataLabel);

        //set component bounds (only needed by Absolute Positioning)
        buyTicketButton.setBounds(255, 95, 100, 20);
        eventScrollPane.setBounds(35, 25, 100, 75);
        jcomp3.setBounds(255, 55, 100, 25);
        dataLabel.setBounds(255, 15, 100, 25);

        setName("Ticket Machine");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setVisible(true);
    }

    public void getTicket(int index) {
        eventArrayList.get(index).setAvailableTickets(eventArrayList.get(index).getAvailableTickets() - 1);
        if (eventArrayList.get(index).getAvailableTickets() == 0)
            eventArrayList.remove(index);
        refreshEvents();
    }

    public void refreshEvents() {
        String[] eventArr = new String[eventArrayList.size()];
        ArrayList<String> temp = new ArrayList<>();
        for (EventTicketMachine event : eventArrayList) {
            temp.add(event.getEventName() + " - " + event.getAvailableTickets());
        }
        eventArr = temp.toArray(eventArr);
        remove(eventScrollPane);
        eventList = new JList(eventArr);
        eventScrollPane = new JScrollPane(eventList);
        eventScrollPane.setBounds(35, 25, 100, 75);
        add(eventScrollPane);
        revalidate();
        repaint();
    }

}
